spring.application.name=springsecurity
server.servlet.context-path=/ssecurity

jwt.public.key=classpath:app.pub
jwt.private.key=classpath:app.key

spring.profiles.active=${APP_PROFILE:dev}
spring.jpa.open-in-view=false

server.port=8080
